//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetDocs.UI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NetDocs.UI.App_GlobalResources.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterar.
        /// </summary>
        public static string Alterar {
            get {
                return ResourceManager.GetString("Alterar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atenção!.
        /// </summary>
        public static string Atencao {
            get {
                return ResourceManager.GetString("Atencao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carregando....
        /// </summary>
        public static string Carregando {
            get {
                return ResourceManager.GetString("Carregando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data alteração.
        /// </summary>
        public static string DataAlteracao {
            get {
                return ResourceManager.GetString("DataAlteracao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data cadastro.
        /// </summary>
        public static string DataCadastro {
            get {
                return ResourceManager.GetString("DataCadastro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalhes.
        /// </summary>
        public static string Detalhes {
            get {
                return ResourceManager.GetString("Detalhes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro!.
        /// </summary>
        public static string Erro {
            get {
                return ResourceManager.GetString("Erro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluir.
        /// </summary>
        public static string Excluir {
            get {
                return ResourceManager.GetString("Excluir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha na operação!.
        /// </summary>
        public static string FalhaOperacao {
            get {
                return ResourceManager.GetString("FalhaOperacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fechar.
        /// </summary>
        public static string Fechar {
            get {
                return ResourceManager.GetString("Fechar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtrar.
        /// </summary>
        public static string Filtrar {
            get {
                return ResourceManager.GetString("Filtrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Há {0} alertas:.
        /// </summary>
        public static string ListaAtencao {
            get {
                return ResourceManager.GetString("ListaAtencao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Há {0} erros:.
        /// </summary>
        public static string ListaErro {
            get {
                return ResourceManager.GetString("ListaErro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Há {0} notificações:.
        /// </summary>
        public static string ListaInfo {
            get {
                return ResourceManager.GetString("ListaInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Há {0} notificações de sucesso:.
        /// </summary>
        public static string ListaSucesso {
            get {
                return ResourceManager.GetString("ListaSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Célula.
        /// </summary>
        public static string MenuCelula {
            get {
                return ResourceManager.GetString("MenuCelula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setor.
        /// </summary>
        public static string MenuSetor {
            get {
                return ResourceManager.GetString("MenuSetor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum registro encontrado.
        /// </summary>
        public static string NenhumRegistroEncontrado {
            get {
                return ResourceManager.GetString("NenhumRegistroEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string Nome {
            get {
                return ResourceManager.GetString("Nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo item.
        /// </summary>
        public static string NovoItem {
            get {
                return ResourceManager.GetString("NovoItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tem certeza de que deseja excluir o registro {0} ?.
        /// </summary>
        public static string PerguntaExcluir {
            get {
                return ResourceManager.GetString("PerguntaExcluir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro alterado!.
        /// </summary>
        public static string RegistroAlterado {
            get {
                return ResourceManager.GetString("RegistroAlterado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;{0}&lt;/b&gt; registro encontrado em &lt;b&gt;{1}&lt;/b&gt; página.
        /// </summary>
        public static string RegistroEncontrado1 {
            get {
                return ResourceManager.GetString("RegistroEncontrado1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;{0}&lt;/b&gt; registros encontrados em &lt;b&gt;{1}&lt;/b&gt; página.
        /// </summary>
        public static string RegistroEncontrado2 {
            get {
                return ResourceManager.GetString("RegistroEncontrado2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;{0}&lt;/b&gt; registros encontrados em &lt;b&gt;{1}&lt;/b&gt; páginas.
        /// </summary>
        public static string RegistroEncontrado3 {
            get {
                return ResourceManager.GetString("RegistroEncontrado3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro excluído!.
        /// </summary>
        public static string RegistroExcluido {
            get {
                return ResourceManager.GetString("RegistroExcluido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro incluído!.
        /// </summary>
        public static string RegistroIncluido {
            get {
                return ResourceManager.GetString("RegistroIncluido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvar.
        /// </summary>
        public static string Salvar {
            get {
                return ResourceManager.GetString("Salvar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alteração de {0}.
        /// </summary>
        public static string SiteMapAlterar {
            get {
                return ResourceManager.GetString("SiteMapAlterar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro de {0}.
        /// </summary>
        public static string SiteMapCadastrar {
            get {
                return ResourceManager.GetString("SiteMapCadastrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Célula.
        /// </summary>
        public static string SiteMapCelula {
            get {
                return ResourceManager.GetString("SiteMapCelula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalhes de {0}.
        /// </summary>
        public static string SiteMapDetalhes {
            get {
                return ResourceManager.GetString("SiteMapDetalhes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sucesso!.
        /// </summary>
        public static string Sucesso {
            get {
                return ResourceManager.GetString("Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterado por.
        /// </summary>
        public static string UsuarioAlteracao {
            get {
                return ResourceManager.GetString("UsuarioAlteracao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criado por.
        /// </summary>
        public static string UsuarioCadastro {
            get {
                return ResourceManager.GetString("UsuarioCadastro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltar.
        /// </summary>
        public static string Voltar {
            get {
                return ResourceManager.GetString("Voltar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data cadastro é obrigatório.
        /// </summary>
        public static string VSDataCadastro {
            get {
                return ResourceManager.GetString("VSDataCadastro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome é obrigatório.
        /// </summary>
        public static string VSNome {
            get {
                return ResourceManager.GetString("VSNome", resourceCulture);
            }
        }
    }
}
