//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetDocs.UI.Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NetDocs.UI.App_GlobalResources.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 1.0.0.
        /// </summary>
        public static string _Versao {
            get {
                return ResourceManager.GetString("_Versao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Alterar.
        /// </summary>
        public static string Alterar {
            get {
                return ResourceManager.GetString("Alterar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Atenção!.
        /// </summary>
        public static string Atencao {
            get {
                return ResourceManager.GetString("Atencao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Carregando....
        /// </summary>
        public static string Carregando {
            get {
                return ResourceManager.GetString("Carregando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data alteração.
        /// </summary>
        public static string DataAlteracao {
            get {
                return ResourceManager.GetString("DataAlteracao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data cadastro.
        /// </summary>
        public static string DataCadastro {
            get {
                return ResourceManager.GetString("DataCadastro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Detalhes.
        /// </summary>
        public static string Detalhes {
            get {
                return ResourceManager.GetString("Detalhes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro!.
        /// </summary>
        public static string Erro {
            get {
                return ResourceManager.GetString("Erro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Excluir.
        /// </summary>
        public static string Excluir {
            get {
                return ResourceManager.GetString("Excluir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Falha na operação!.
        /// </summary>
        public static string FalhaOperacao {
            get {
                return ResourceManager.GetString("FalhaOperacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fechar.
        /// </summary>
        public static string Fechar {
            get {
                return ResourceManager.GetString("Fechar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Filtrar.
        /// </summary>
        public static string Filtrar {
            get {
                return ResourceManager.GetString("Filtrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Há {0} alertas:.
        /// </summary>
        public static string ListaAtencao {
            get {
                return ResourceManager.GetString("ListaAtencao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Há {0} erros:.
        /// </summary>
        public static string ListaErro {
            get {
                return ResourceManager.GetString("ListaErro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Há {0} notificações:.
        /// </summary>
        public static string ListaInfo {
            get {
                return ResourceManager.GetString("ListaInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Há {0} notificações de sucesso:.
        /// </summary>
        public static string ListaSucesso {
            get {
                return ResourceManager.GetString("ListaSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Célula.
        /// </summary>
        public static string MenuCelula {
            get {
                return ResourceManager.GetString("MenuCelula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Setor.
        /// </summary>
        public static string MenuSetor {
            get {
                return ResourceManager.GetString("MenuSetor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nenhum registro encontrado.
        /// </summary>
        public static string NenhumRegistroEncontrado {
            get {
                return ResourceManager.GetString("NenhumRegistroEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome.
        /// </summary>
        public static string Nome {
            get {
                return ResourceManager.GetString("Nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Novo item.
        /// </summary>
        public static string NovoItem {
            get {
                return ResourceManager.GetString("NovoItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tem certeza de que deseja excluir o registro {0} ?.
        /// </summary>
        public static string PerguntaExcluir {
            get {
                return ResourceManager.GetString("PerguntaExcluir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Registro alterado!.
        /// </summary>
        public static string RegistroAlterado {
            get {
                return ResourceManager.GetString("RegistroAlterado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;b&gt;{0}&lt;/b&gt; registro encontrado em &lt;b&gt;{1}&lt;/b&gt; página.
        /// </summary>
        public static string RegistroEncontrado1 {
            get {
                return ResourceManager.GetString("RegistroEncontrado1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;b&gt;{0}&lt;/b&gt; registros encontrados em &lt;b&gt;{1}&lt;/b&gt; página.
        /// </summary>
        public static string RegistroEncontrado2 {
            get {
                return ResourceManager.GetString("RegistroEncontrado2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;b&gt;{0}&lt;/b&gt; registros encontrados em &lt;b&gt;{1}&lt;/b&gt; páginas.
        /// </summary>
        public static string RegistroEncontrado3 {
            get {
                return ResourceManager.GetString("RegistroEncontrado3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Registro excluído!.
        /// </summary>
        public static string RegistroExcluido {
            get {
                return ResourceManager.GetString("RegistroExcluido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Registro incluído!.
        /// </summary>
        public static string RegistroIncluido {
            get {
                return ResourceManager.GetString("RegistroIncluido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Salvar.
        /// </summary>
        public static string Salvar {
            get {
                return ResourceManager.GetString("Salvar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Alteração de {0}.
        /// </summary>
        public static string SiteMapAlterar {
            get {
                return ResourceManager.GetString("SiteMapAlterar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cadastro de {0}.
        /// </summary>
        public static string SiteMapCadastrar {
            get {
                return ResourceManager.GetString("SiteMapCadastrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Célula.
        /// </summary>
        public static string SiteMapCelula {
            get {
                return ResourceManager.GetString("SiteMapCelula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Detalhes de {0}.
        /// </summary>
        public static string SiteMapDetalhes {
            get {
                return ResourceManager.GetString("SiteMapDetalhes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sucesso!.
        /// </summary>
        public static string Sucesso {
            get {
                return ResourceManager.GetString("Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Alterado por.
        /// </summary>
        public static string UsuarioAlteracao {
            get {
                return ResourceManager.GetString("UsuarioAlteracao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Criado por.
        /// </summary>
        public static string UsuarioCadastro {
            get {
                return ResourceManager.GetString("UsuarioCadastro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Voltar.
        /// </summary>
        public static string Voltar {
            get {
                return ResourceManager.GetString("Voltar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data cadastro é obrigatório.
        /// </summary>
        public static string VSDataCadastro {
            get {
                return ResourceManager.GetString("VSDataCadastro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome é obrigatório.
        /// </summary>
        public static string VSNome {
            get {
                return ResourceManager.GetString("VSNome", resourceCulture);
            }
        }
    }
}
